### ISSUE TITLE
crashing error for the app

### ISSUE THREAD

**Issue by frizzyice** [DigitalPhantom/PhantomWeatherAndroid#12]
hi , i keep getting crashes on the app saying that "Unfortunately, the application has stopped."

here is the logcat

 --------- beginning of crash
05-09 01:05:45.336 2516-2516/eng.edu.tp.weathertest.weathertest E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: eng.edu.tp.weathertest.weathertest, PID: 2516
                                                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                                                      at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
                                                                                      at org.json.JSONTokener.nextValue(JSONTokener.java:94)
                                                                                      at org.json.JSONObject.<init>(JSONObject.java:156)
                                                                                      at org.json.JSONObject.<init>(JSONObject.java:173)
                                                                                      at eng.edu.tp.weathertest.weathertest.service.YahooWeatherService$1.onPostExecute(YahooWeatherService.java:76)
                                                                                      at eng.edu.tp.weathertest.weathertest.service.YahooWeatherService$1.onPostExecute(YahooWeatherService.java:35)
                                                                                      at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                                      at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                                      at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by tarunkukreja003** [comment]
I am facing the same problem

**Comment by ynunez** [comment]
@frizzyice @tarunkukreja003 I cannot reproduce the issue. are you using the latest version of the code. If not try doing so and let me know how it goes.
