### ISSUE TITLE
Crashing on first start

### ISSUE THREAD

**Issue by iven86** [DigitalPhantom/PhantomWeatherAndroid#18]
please your help to fix it
and below android monitor 

08-12 18:30:41.454 6448-7078/net.digitalphantom.app.weatherapp E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                                                 Process: net.digitalphantom.app.weatherapp, PID: 6448
                                                                                 java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                     at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                                     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                                     at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
                                                                                     at net.digitalphantom.app.weatherapp.service.YahooWeatherService$1.doInBackground(YahooWeatherService.java:68)
                                                                                     at net.digitalphantom.app.weatherapp.service.YahooWeatherService$1.doInBackground(YahooWeatherService.java:60)
                                                                                     at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                     at java.lang.Thread.run(Thread.java:818) 
08-12 18:30:42.409 6448-6448/net.digitalphantom.app.weatherapp D/ViewRootImpl: #3 mView = null
08-12 18:30:42.419 6448-6448/net.digitalphantom.app.weatherapp E/WindowManager: android.view.WindowLeaked: Activity net.digitalphantom.app.weatherapp.WeatherActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{c5049e V.E...... R......D 0,0-1336,464} that was originally added here
                                                                                    at android.view.ViewRootImpl.<init>(ViewRootImpl.java:565)
                                                                                    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:326)
                                                                                    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:91)
                                                                                    at android.app.Dialog.show(Dialog.java:350)
                                                                                    at net.digitalphantom.app.weatherapp.WeatherActivity.onStart(WeatherActivity.java:111)
                                                                                    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1265)
                                                                                    at android.app.Activity.performStart(Activity.java:6915)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3216)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
                                                                                    at android.app.ActivityThread.access$1100(ActivityThread.java:221)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:158)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:7225)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
08-12 18:30:42.419 6448-6448/net.digitalphantom.app.weatherapp E/WindowManager: android.view.WindowLeaked: Activity net.digitalphantom.app.weatherapp.WeatherActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{865086 V.E...... R......D 0,0-1336,464} that was originally added here
                                                                                    at android.view.ViewRootImpl.<init>(ViewRootImpl.java:565)
                                                                                    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:326)
                                                                                    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:91)
                                                                                    at android.app.Dialog.show(Dialog.java:350)
                                                                                    at net.digitalphantom.app.weatherapp.WeatherActivity.onStart(WeatherActivity.java:111)
                                                                                    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1265)
                                                                                    at android.app.Activity.performStart(Activity.java:6915)
                                                                                    at android.app.Activity.performRestart(Activity.java:6974)
                                                                                    at android.app.Activity.performResume(Activity.java:6979)
                                                                                    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4144)
                                                                                    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4246)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1838)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:158)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:7225)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
08-12 18:30:42.419 6448-6448/net.digitalphantom.app.weatherapp D/ViewRootImpl: #3 mView = null
08-12 18:30:42.449 6448-6448/net.digitalphantom.app.weatherapp D/ViewRootImpl: #3 mView = null

**Comment by iven86** [comment]
Any update please
