### ISSUE TITLE
Problem when running application

### ISSUE THREAD

**Issue by NickMcGinnis** [DigitalPhantom/PhantomWeatherAndroid#7]
FATAL EXCEPTION: main
    Process: com.example.tinma_000.weather, PID: 30381
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setImageDrawable(android.graphics.drawable.Drawable)' on a null object reference
            at com.example.tinma_000.weather.WeatherActivity.serviceSuccess(WeatherActivity.java:54)
            at com.example.tinma_000.weather.service.YahooWeatherService$1.onPostExecute(YahooWeatherService.java:89)
            at com.example.tinma_000.weather.service.YahooWeatherService$1.onPostExecute(YahooWeatherService.java:36)
            at android.os.AsyncTask.finish(AsyncTask.java:632)
            at android.os.AsyncTask.access$600(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5972)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by NickMcGinnis** [comment]
I discovered what was wrong, I named the WeatherIconImageViewer with a capital W, in my code I referenced weatherIconImageViewer, causing it to point to a null object, silly me.

**Comment by ynunez** [comment]
@NickMcGinnis I'm glad you found the solutions
